	<footer>
		<div class="grid__item one-whole line"><hr></div><!--
		 --><nav class="footernav">
			<ul class="nav">
				<li><a href="index.php">Startseite</a></li>
				<li><a href="#">Presse</a></li>
				<li><a href="downloads.php">Downloads</a></li>
				<li><a href="kontakt.php">Kontakt</a></li>
				<li><a href="#">AGB</a></li>
				<li><a href="#">Impressum</a></li>
			</ul>
		</nav><!--
		 --><div class="search">
			<form action="#" method="post" class="inline-form search-form">
			    <fieldset>
				    <legend class="is-vishidden">Search</legend>
				    <label for="search-field" class="is-vishidden">Search</label>
				    <input type="search" placeholder="" id="search-field" class="search-field">
				    <input type="submit" value="Suchen" class="search-submit">
			    </fieldset>
			</form>
		</div><!--
		 --><div class="copyright">
			&copy; 2013 Korona Leuchten GmbH
		</div>
	</footer>
	<script src="<?php echo $config->urls->templates?>js/jquery.min.js"></script>
	<script src="<?php echo $config->urls->templates?>js/init.js"></script>
</body>
</html>